// DT-FE-12: los textos de la interfaz viven aquí para poder traducirla sin tocar las plantillas
export const TEXTOS = {
  offline: {
    titulo: 'Base offline — datos ficticios',
    propietario: 'Propietario ficticio',
    crear: 'Crear inspección ficticia',
    guardar: 'Guardar respuestas',
    guardado: 'Guardado local confirmado',
    respuestas: 'Respuestas JSON',
    jsonInvalido: 'Las respuestas deben ser JSON válido',
    anclaje: 'Anclaje de la foto',
    pdf: 'Adjuntar PDF',
    enviar: 'Registrar intención de envío',
    sincronizar: 'Sincronizar simulación',
    reintentar: 'Reintentar',
    resultado: 'Resultado del transporte simulado',
    ack: 'Confirmación simulada',
    transitorio: 'Fallo transitorio',
    negocio: 'Rechazo de negocio',
    sesion: 'Sesión inválida',
    inspecciones: 'Inspecciones pendientes',
    archivos: 'Archivos pendientes',
    ocupacion: 'Ocupación del origen (bytes)',
    cuota: 'Cuota del origen (bytes)',
    persistente: 'Almacenamiento persistente concedido',
    noPersistente: 'Persistencia denegada: el navegador puede eliminar los datos',
    sinApi: 'API de almacenamiento no disponible',
    almacenamientoError: 'No se pudo consultar el almacenamiento',
    escrituraError: 'No se pudo guardar. Comprueba el espacio disponible.',
    cuotaError: 'No hay cuota suficiente. El guardado no se realizó.',
    propietarioInvalido: 'Se requiere el UUID del propietario',
    noDisponible: 'Registro no disponible para este propietario',
    fotoInvalida: 'La foto requiere anclaje y blobs WebP/JPEG',
    pdfInvalido: 'Se requiere PDF de hasta 20 MB',
    limiteArchivos: 'Se alcanzó el límite de archivos',
    ultimoIntento: 'Último intento',
    dependencias: 'Dependencias pendientes',
    intentos: 'Fallos consecutivos',
    siguiente: 'Próximo intento',
    estado: 'Estado',
    errorTransporte: 'Fallo de transporte',
    ackInvalido: 'Confirmación incompatible con la operación',
    pausa: 'Sincronización pausada por sesión',
    desconocido: 'No disponible',
    ninguna: 'Ninguno',
    lista: 'Operaciones locales',
    inspeccion: 'Inspección',
    fotos: 'Fotos guardadas',
    documentos: 'PDF guardados',
  },
  capturaFoto: {
    boton: 'Tomar o elegir foto',
    procesando: 'Procesando foto…',
    error: 'No se pudo leer la imagen. Intenta con otra foto.',
  },
} as const;
